import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import { useState } from 'react';
import { ActivityIndicator, Image, Platform, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SalonLocationPicker } from '@/components/salon-location-picker';
import { createOwnerSalon } from '@/services/api';

export function OwnerSalonSetupScreen({ token, defaultName, onComplete, onLogout }: { token: string; defaultName: string; onComplete: () => void; onLogout: () => void }) {
  const [name,setName]=useState(defaultName); const [address,setAddress]=useState(''); const [city,setCity]=useState('Nasugbu');
  const [latitude,setLatitude]=useState('14.0667'); const [longitude,setLongitude]=useState('120.6333');
  const [logoUri,setLogoUri]=useState<string|null>(null); const [logoData,setLogoData]=useState<string|undefined>(); const [saving,setSaving]=useState(false); const [error,setError]=useState<string|null>(null);
  const pickLogo=async()=>{ if(Platform.OS!=='web'){const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return;} const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,aspect:[1,1],quality:.65,base64:true});if(result.canceled)return;const asset=result.assets[0];if(!asset.base64)return;const mime=['image/jpeg','image/png','image/webp'].includes(asset.mimeType||'')?asset.mimeType:'image/jpeg';setLogoUri(asset.uri);setLogoData(`data:${mime};base64,${asset.base64}`);};
  const save=async()=>{setSaving(true);setError(null);try{await createOwnerSalon(token,{name,address,city,latitude:Number(latitude),longitude:Number(longitude),logoData});onComplete();}catch(reason){setError(reason instanceof Error?reason.message:'Unable to create salon.');}finally{setSaving(false);}};
  return <><View style={s.header}><View><Text style={s.kicker}>OWNER SETUP</Text><Text style={s.title}>Finish your salon profile</Text></View><Pressable onPress={onLogout} style={s.logout}><Ionicons name="log-out-outline" size={18} color="#A94F67" /></Pressable></View><Text style={s.body}>Your account exists, but its salon still needs to be linked. Pin the exact location customers should see.</Text><Field label="Salon name" value={name} onChange={setName}/><Field label="Complete address" value={address} onChange={setAddress}/><Field label="City or municipality" value={city} onChange={setCity}/><Pressable onPress={()=>void pickLogo()} style={s.logoPicker}>{logoUri?<Image source={{uri:logoUri}} style={s.logo}/>:<Ionicons name="images-outline" size={30} color="#A94F67"/>}<Text style={s.logoText}>{logoUri?'Change salon logo':'Add salon logo'}</Text></Pressable><Text style={s.label}>PIN SALON LOCATION</Text><SalonLocationPicker latitude={Number(latitude)||14.0667} longitude={Number(longitude)||120.6333} onChange={point=>{setLatitude(point.latitude.toFixed(7));setLongitude(point.longitude.toFixed(7));}}/><View style={s.row}><View style={s.half}><Field label="Latitude" value={latitude} onChange={setLatitude}/></View><View style={s.half}><Field label="Longitude" value={longitude} onChange={setLongitude}/></View></View>{error&&<Text style={s.error}>{error}</Text>}<Pressable disabled={saving} onPress={()=>void save()} style={s.save}>{saving?<ActivityIndicator color="#fff"/>:<><Ionicons name="checkmark" size={20} color="#fff"/><Text style={s.saveText}>Create and publish salon</Text></>}</Pressable></>;
}
function Field({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <View style={s.fieldWrap}><Text style={s.label}>{label}</Text><TextInput value={value} onChangeText={onChange} style={s.field}/></View>}
const s=StyleSheet.create({header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginBottom:12},kicker:{fontSize:10,fontWeight:'900',letterSpacing:1.2,color:'#A94F67'},title:{fontSize:25,fontWeight:'900',color:'#292326'},body:{fontSize:14,lineHeight:21,color:'#7C7074',marginBottom:18},logout:{width:42,height:42,borderRadius:21,backgroundColor:'#fff',alignItems:'center',justifyContent:'center'},fieldWrap:{marginBottom:13},label:{fontSize:10,fontWeight:'900',letterSpacing:.8,color:'#743548',marginBottom:7},field:{height:53,borderRadius:16,backgroundColor:'#fff',borderWidth:1,borderColor:'#EDE3E5',paddingHorizontal:14,fontSize:14,color:'#292326'},logoPicker:{minHeight:78,borderRadius:18,backgroundColor:'#fff',borderWidth:1,borderStyle:'dashed',borderColor:'#D9B4BE',padding:12,flexDirection:'row',alignItems:'center',gap:12,marginBottom:18},logo:{width:54,height:54,borderRadius:15},logoText:{fontSize:13,fontWeight:'800',color:'#743548'},row:{flexDirection:'row',gap:10},half:{flex:1},error:{padding:12,borderRadius:12,backgroundColor:'#FCE8EC',color:'#81263A',marginBottom:10},save:{minHeight:54,borderRadius:18,backgroundColor:'#A94F67',flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},saveText:{fontSize:15,fontWeight:'900',color:'#fff'}});
